import {
  AlarmSmoke,
  Bath,
  BriefcaseMedical,
  Building2,
  CalendarDays,
  Car,
  Castle,
  Coffee,
  Dumbbell,
  Fence,
  FireExtinguisher,
  Flame,
  FlameKindling,
  Heater,
  House,
  KeyRound,
  Landmark,
  Laptop,
  type LucideIcon,
  Mountain,
  MountainSnow,
  Palmtree,
  PawPrint,
  PenTool,
  PlugZap,
  Sailboat,
  Shirt,
  Snowflake,
  Sparkles,
  Tractor,
  TreePine,
  Trees,
  Tv,
  Umbrella,
  Utensils,
  WashingMachine,
  Waves,
  WavesLadder,
  Wheat,
  Wifi,
  Wind,
} from "lucide-react";

// Categories and amenities store an icon key in the database; this maps keys to SVG icons.
const ICONS: Record<string, LucideIcon> = {
  "alarm-smoke": AlarmSmoke,
  bath: Bath,
  "briefcase-medical": BriefcaseMedical,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  car: Car,
  castle: Castle,
  coffee: Coffee,
  dumbbell: Dumbbell,
  fence: Fence,
  "fire-extinguisher": FireExtinguisher,
  flame: Flame,
  "flame-kindling": FlameKindling,
  heater: Heater,
  house: House,
  "key-round": KeyRound,
  landmark: Landmark,
  laptop: Laptop,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  palmtree: Palmtree,
  "paw-print": PawPrint,
  "pen-tool": PenTool,
  "plug-zap": PlugZap,
  sailboat: Sailboat,
  shirt: Shirt,
  snowflake: Snowflake,
  tractor: Tractor,
  "tree-pine": TreePine,
  trees: Trees,
  tv: Tv,
  umbrella: Umbrella,
  utensils: Utensils,
  "washing-machine": WashingMachine,
  waves: Waves,
  "waves-ladder": WavesLadder,
  wheat: Wheat,
  wifi: Wifi,
  wind: Wind,
};

export function Icon({ name, size = 24, className }: { name: string; size?: number; className?: string }) {
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp size={size} strokeWidth={1.5} className={className} aria-hidden />;
}
